# Generated by Django 4.1.7 on 2023-05-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatting',
            name='chattts',
            field=models.CharField(max_length=1000000),
        ),
    ]
