# Generated by Django 4.1.7 on 2023-05-06 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0002_alter_chatting_chattts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
