# Generated by Django 4.1.7 on 2023-05-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0003_chatting_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='cusrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chj.chatting'),
        ),
    ]
