# Generated by Django 4.1.7 on 2023-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0004_chatting_cusrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='useridhtml',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
