# Generated by Django 4.1.7 on 2023-06-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0005_chatting_useridhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatting',
            name='cusrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chj.chatting'),
        ),
    ]
