# Generated by Django 4.1.7 on 2023-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0006_alter_chatting_cusrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='cccc',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
