# Generated by Django 4.1.7 on 2023-06-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chj', '0007_chatting_cccc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='cccc',
        ),
    ]
